name: Ruby Project
services:
  web:
    image: ruby_backend
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: secretpassword
      DB_NAME: project1
      RAILS_ENV: development
    stop_grace_period: 30s
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - ruby_project
    command: sh -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0"
  front:
    image: ruby_frontend
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - ruby_project
    command: sh -c "nginx -g 'daemon off;'"

networks:
  ruby_project:
volumes:
  pg_data:
