name: Upload to EC2

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push docker
      run: |
        docker build -t {{ secret.DOCKERNAME }}/ruby_backend .
        docker push {{ secret.DOCKERNAME }}/ruby_backend   
    - name: Deploy Docker to EC2
      run: |
        touch password.pem
        echo "${{ secrets.SECRET_KEY_PAIR }}" >> password.pem
        chmod 400 password.pem
        ssh -i password.pem -t -t -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_ADDRESS }} << 'EOF'
        docker rm ruby_backend
        docker rmi {{ secret.DOCKERNAME }}/ruby_backend
        docker pull {{ secret.DOCKERNAME }}/ruby_backend
        docker run -d -p 3000:3000 -e DATABASE_PASSWORD=secretpassword -e DATABASE_HOST=ruby-on-rails-230306.c21epmfqzrpf.us-east-2.rds.amazonaws.com --network ruby_project joshet/ruby_backend
        screen -d -m
        exit
        EOF

  
