name: deploy to ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    # self-hosted runner is linked to Josh's EC2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Uses Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - run: rails start
